### ISSUE TITLE
Investigate flaky test: `TestFailingExpandSeriesValidPools`

### ISSUE THREAD

**Issue by prateek** [m3db/m3#1049]
Works fine with one run:
```
~/code/gocode/src/github.com/m3db/m3 master
❯ go test ./src/query/storage -run TestFailingExpandSeriesValidPools -count 1 -timeout 10s
ok  	github.com/m3db/m3/src/query/storage	0.029s
```

But crashes when count is higher: 
```
~/code/gocode/src/github.com/m3db/m3 master
❯ go test ./src/query/storage -run TestFailingExpandSeriesValidPools -count 10 -timeout 10s
panic: test timed out after 10s
```

<details>
<summary>Stacktrace</summary>

```
goroutine 23 [running]:
testing.(*M).startAlarm.func1()
	/Users/prungta/code/go1.10.2/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/Users/prungta/code/go1.10.2/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4203de0f0, 0x1584af1, 0x21, 0x15978e0, 0x1077b01)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc4203de000)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc4203de000, 0xc4203c7df8)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4202fc3e0, 0x1871300, 0xb, 0xb, 0x1012149)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420398080, 0x0)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:64 +0x151

goroutine 44 [chan send]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).Go(0xc4202ee660, 0xc4202eea20)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:97 +0x1a3
github.com/m3db/m3/src/query/storage.decompressConcurrently(0x10, 0xc420486100, 0x10, 0x10, 0x15d7c60, 0xc4202ee660, 0x0, 0x0, 0x0)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/src/query/storage/converter.go:275 +0x163
github.com/m3db/m3/src/query/storage.SeriesIteratorsToFetchResult(0x15d9620, 0xc420363290, 0x15d7c60, 0xc4202ee660, 0xc42036fa01, 0x0, 0x0, 0x0)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/src/query/storage/converter.go:322 +0xd9
github.com/m3db/m3/src/query/storage.TestFailingExpandSeriesValidPools(0xc4203de0f0)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/src/query/storage/converter_test.go:121 +0xf6e
testing.tRunner(0xc4203de0f0, 0x15978e0)
	/Users/prungta/code/go1.10.2/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/Users/prungta/code/go1.10.2/src/testing/testing.go:824 +0x2e0

goroutine 36 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202f24e0, 0x0, 0x152ca78d152ca78d, 0xc4202f2420, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 37 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202f24e0, 0x0, 0x27c6003027c6003, 0xc4202f2480, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 8 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4200807e0, 0x0, 0x152ca78d152ca78d, 0xc420080720, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 9 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4200807e0, 0x0, 0x27c6003027c6003, 0xc420080780, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 40 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202f2d80, 0x0, 0x152ca78d152ca78d, 0xc4202f2cc0, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 41 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202f2d80, 0x0, 0x27c6003027c6003, 0xc4202f2d20, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 21 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202ee8a0, 0x0, 0x152ca78d152ca78d, 0xc4202ee7e0, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 22 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202ee8a0, 0x0, 0x27c6003027c6003, 0xc4202ee840, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 12 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc420081020, 0x0, 0x152ca78d152ca78d, 0xc420080f60, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 13 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc420081020, 0x0, 0x27c6003027c6003, 0xc420080fc0, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66

goroutine 45 [chan receive]:
github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc4202ee660, 0x0, 0x152ca78d152ca78d, 0xc4202ee5a0, 0x1)
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:140 +0x147
created by github.com/m3db/m3/vendor/github.com/m3db/m3x/sync.(*pooledWorkerPool).spawnWorker
	/Users/prungta/code/gocode/src/github.com/m3db/m3/vendor/github.com/m3db/m3x/sync/pooled_worker_pool.go:121 +0x66
FAIL	github.com/m3db/m3/src/query/storage	10.032s
```

</details>

[E.g. Failure log from CI](https://buildkite.com/organizations/m3/pipelines/m3-monorepo-ci/builds/471/jobs/e945e156-4079-45e8-81ce-5e32540a4c40/artifacts/3760ca5d-fca8-4eff-a8c1-a1eae162c7f1)

**Comment by prateek** [comment]
@arnikola mind taking a look, I think it's a recently added test

**Comment by arnikola** [comment]
Resolved in: https://github.com/m3db/m3/pull/1052
