### ISSUE TITLE
m3db panics, SIGSEGV in dbnode/storage/index.go:queryWithSpan()

### ISSUE THREAD

**Issue by mmedvede** [m3db/m3#2439]
We have experienced repeated SIGSEGV on a few nodes in a small m3db cluster
that have been recently upgraded to `v0.15.3`

```
 Go Runtime version: go1.13.8
 Build Version:      v0.15.3
 Build Revision:     ec34fe0c8
 Build Branch:       master
 Build Date:         2020-06-23-18:37:52
 Build TimeUnix:     1592951872
```

The cluster started getting more writes to one of
namespaces, and the panics followed. Same stacktrace every time:

```
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc4b57e]
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: goroutine 424626916 [running]:
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3dbx/vellum.(*FSTIterator).stateGet(0xc158e8d600, 0x75, 0x5, 0x75, 0xe911, 0x20)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:117 +0xae
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3dbx/vellum.(*FSTIterator).next(0xc158e8d600, 0xffffffffffffffff, 0xccda0a, 0xc108654b40)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:253 +0x1d6
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3dbx/vellum.(*FSTIterator).Next(...)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:219
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsIter).Next(0xc19b76d6d0, 0xa)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_iterator.go:94 +0xbc
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).setNextField(0xc2297265a0, 0x0)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:108 +0x57
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).Next(0xc2297265a0, 0xc04a4c2000)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:173 +0x54
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage/index.(*block).aggregateWithSpan(0xc108654b40, 0x215ac40, 0xc065b61180, 0xc0cdb2eea0, 0x7ab1e00, 0xce288ee1d, 0x2ff37e0, 0x389d89d7, 0xed68c65d4, 0x2ff37e0, ...)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:659 +0x3ee
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage/index.(*block).Aggregate(0xc108654b40, 0x215ac40, 0xc065b61180, 0xc0cdb2eea0, 0x7ab1e00, 0xce288ee1d, 0x2ff37e0, 0x389d89d7, 0xed68c65d4, 0x2ff37e0, ...)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:572 +0x1c3
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn(0xc088adb180, 0x215ac40, 0xc065b61180, 0xc0cdb2eea0, 0x2161d00, 0xc108654b40, 0x2135160, 0x3014598, 0x7ab1e00, 0xce288ee1d, ...)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1484 +0x8fe
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).queryWithSpan.func2()
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1352 +0x150
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout.func1(0xc22880b050, 0xc0004ea0d8)
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:68 +0x27
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: created by github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout
Jun 29 22:44:36 dbnode-500173825-1-729654367 m3dbnode[121335]: /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:67 +0x122
Jun 29 22:44:38 dbnode-500173825-1-729654367 systemd[1]: m3dbnode.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

There is nothing in the log prior to the panic.

## Grafana screenshots
![Screenshot_2020-07-01 M3DB Node Details - Grafana](https://user-images.githubusercontent.com/1115468/86267187-ded1fd80-bbb5-11ea-8b54-203adb530173.png)
![Screenshot_2020-07-01 M3DB Node Details - Grafana(1)](https://user-images.githubusercontent.com/1115468/86267208-e691a200-bbb5-11ea-888b-e9dfbe21d07f.png)
![Screenshot_2020-07-01 M3DB Node Details - Grafana(2)](https://user-images.githubusercontent.com/1115468/86267225-ec878300-bbb5-11ea-8906-057d8783a68f.png)
![Screenshot_2020-07-01 M3DB Node Details - Grafana(3)](https://user-images.githubusercontent.com/1115468/86267242-f1e4cd80-bbb5-11ea-88f6-8e6a6c25d3f2.png)

## Config / logs / debug dumps
[dump.10.12.37.60.zip](https://github.com/m3db/m3/files/4859062/dump.10.12.37.60.zip)
[dump.10.12.37.61.zip](https://github.com/m3db/m3/files/4859063/dump.10.12.37.61.zip)
[m3dbnode-config.yml.zip](https://github.com/m3db/m3/files/4859069/m3dbnode-config.yml.zip)
[panic.10.12.37.61.log.zip](https://github.com/m3db/m3/files/4859071/panic.10.12.37.61.log.zip)
[panic.10.12.37.62.log.zip](https://github.com/m3db/m3/files/4859072/panic.10.12.37.62.log.zip)

**Comment by gibbscullen** [comment]
Thanks -- we will take a look!

**Comment by mmedvede** [comment]
Observed another SIGSEGV, with v0.15.5
```
Go Runtime version: go1.13.12                     
Build Version:      v0.15.5                       
Build Revision:     dd0012723                     
Build Branch:       r/namespace-runtime-options   
Build Date:         2020-07-09-06:28:04           
Build TimeUnix:     1594290484                    
```

This time 3 dbnodes across 3 isolation groups crashed at the same time (within a few seconds), with this stacktrace:

```
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: unexpected fault address 0x7f131ea5c85d
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: fatal error: fault
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f131ea5c85d pc=0xc49197]
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: goroutine 4802983789 [running]:
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: runtime.throw(0x1d921b8, 0x5)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /usr/local/Cellar/go@1.13/1.13.12/libexec/src/runtime/panic.go:774 +0x72 fp=0xc004769110 sp=0xc0047690e0 pc=0x42f552
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: runtime.sigpanic()
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /usr/local/Cellar/go@1.13/1.13.12/libexec/src/runtime/signal_unix.go:401 +0x3de fp=0xc004769140 sp=0xc004769110 pc=0x444c8e
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3dbx/vellum.(*fstStateV1).isEncodedSingle(...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/decoder_v1.go:100
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3dbx/vellum.(*fstStateV1).TransitionAt(0xc0c2fd3e00, 0x1, 0x40)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/decoder_v1.go:231 +0x27 fp=0xc004769160 sp=0xc004769140 pc=0xc49197
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3dbx/vellum.(*FSTIterator).next(0xc4955e0300, 0xffffffffffffffff, 0xc072f33720, 0x1b96620)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:243 +0x120 fp=0xc004769240 sp=0xc004769160 pc=0xc4dfd0
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3dbx/vellum.(*FSTIterator).Next(...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:219
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsIter).Next(0xc39b707360, 0xc072f33720)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_iterator.go:94 +0xbc fp=0xc004769288 sp=0xc004769240 pc=0xc6dd9c
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsPostingsIter).Next(0xc68bf57da0, 0xc39ea96dc0)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_postings_iterator.go:90 +0x3e fp=0xc0047692c0 sp=0xc004769288 pc=0xc6e65e
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).nextTermsIterResult(0xc013bb6f20, 0x10000c00da16801, 0x0, 0x0)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:223 +0x38 fp=0xc004769300 sp=0xc0047692c0 pc=0xcd6418
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).setNext(0xc013bb6f20, 0x200)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:182 +0x1f7 fp=0xc004769350 sp=0xc004769300 pc=0xcd6367
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).Next(0xc013bb6f20, 0xc0647fe000)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:265 +0x38 fp=0xc004769370 sp=0xc004769350 pc=0xcd6678
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage/index.(*block).aggregateWithSpan(0xc39ea96dc0, 0x217c1a0, 0xc3e6a59f10, 0xc546d39d00, 0x7ab1e00, 0xce288ee1d, 0x302cb20, 0x2b196f70, 0xed6a915a8, 0x302cb20, ...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:680 +0x41b fp=0xc004769758 sp=0xc004769370 pc=0xcd0fcb
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage/index.(*block).Aggregate(0xc39ea96dc0, 0x217c1a0, 0xc3e6a59f10, 0xc546d39d00, 0x7ab1e00, 0xce288ee1d, 0x302cb20, 0x2b196f70, 0xed6a915a8, 0x302cb20, ...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:592 +0x1c3 fp=0xc004769900 sp=0xc004769758 pc=0xcd0983
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn(0xc0250a3400, 0x217c1a0, 0xc3e6a59f10, 0xc546d39d00, 0x21834c0, 0xc39ea96dc0, 0x2156ce0, 0xc9a28535e0, 0x7ab1e00, 0xce288ee1d, ...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1670 +0x8fe fp=0xc004769da0 sp=0xc004769900 pc=0x108958e
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn-fm(0x217c1a0, 0xc3e6a59f10, 0xc546d39d00, 0x21834c0, 0xc39ea96dc0, 0x2156ce0, 0xc9a28535e0, 0x7ab1e00, 0xce288ee1d, 0x302cb20, ...)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1642 +0x124 fp=0xc004769e78 sp=0xc004769da0 pc=0x10dd534
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).queryWithSpan.func2()
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1538 +0x150 fp=0xc004769fb0 sp=0xc004769e78 pc=0x10cb6b0
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout.func1(0xc203df97a0, 0xc00000e0d8)
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: /Users/r/go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:68 +0x27 fp=0xc004769fd0 sp=0xc004769fb0 pc=0xc0ffc7
Jul 21 17:00:19 dbnode-897773110-13-900689243 m3dbnode[108274]: runtime.goexit()
```

**Comment by mmedvede** [comment]
Still seeing the same with a custom build off of v0.15.6

```
-- Logs begin at Tue 2020-07-28 03:39:01 UTC, end at Tue 2020-08-18 22:48:20 UTC. --
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc4d20e]
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: goroutine 88272442 [running]:
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3dbx/vellum.(*FSTIterator).stateGet(0xc13978de00, 0x0, 0x0, 0x0, 0x55, 0x20)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/pkg/mod/github.com/mmedvede/m3dbx-vellum@v0.0.0-20200812021150-588b14468dbc/fst_iterator.go:117 +0xae
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3dbx/vellum.(*FSTIterator).next(0xc13978de00, 0xffffffffffffffff, 0xcd31fa, 0xc1e4f04c60)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/pkg/mod/github.com/mmedvede/m3dbx-vellum@v0.0.0-20200812021150-588b14468dbc/fst_iterator.go:253 +0x1d6
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3dbx/vellum.(*FSTIterator).Next(...)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/pkg/mod/github.com/mmedvede/m3dbx-vellum@v0.0.0-20200812021150-588b14468dbc/fst_iterator.go:219
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsIter).Next(0xc2ad54f2c0, 0x3)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_iterator.go:94 +0xbc
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).setNextField(0xc14c701080, 0x0)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:166 +0x57
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).Next(0xc14c701080, 0xc0649cd000)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:262 +0x54
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage/index.(*block).aggregateWithSpan(0xc1e4f04c60, 0x218aca0, 0xc15d740070, 0xc079f653e0, 0x7ab1e00, 0xce288ee1d, 0x30382a0, 0x7acbdcc, 0xed6ce40a8, 0x30382a0, ...)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:680 +0x41b
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage/index.(*block).Aggregate(0xc1e4f04c60, 0x218aca0, 0xc15d740070, 0xc079f653e0, 0x7ab1e00, 0xce288ee1d, 0x30382a0, 0x7acbdcc, 0xed6ce40a8, 0x30382a0, ...)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:592 +0x1c3
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn(0xc049a4b800, 0x218aca0, 0xc15d740070, 0xc079f653e0, 0x2192080, 0xc1e4f04c60, 0x21656a0, 0x3058f50, 0x7ab1e00, 0xce288ee1d, ...)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1663 +0x8fe
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/dbnode/storage.(*nsIndex).queryWithSpan.func2()
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1531 +0x150
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout.func1(0xc0d92661b0, 0xc000bec000)
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:68 +0x27
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: created by github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout
Aug 18 21:35:36 dbnode-500173825-3-729654382 m3dbnode[79459]: /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:67 +0x122
Aug 18 21:35:38 dbnode-500173825-3-729654382 systemd[1]: m3dbnode.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 21:35:38 dbnode-500173825-3-729654382 systemd[1]: Unit m3dbnode.service entered failed state.
Aug 18 21:35:38 dbnode-500173825-3-729654382 systemd[1]: m3dbnode.service failed.
Aug 18 21:35:48 dbnode-500173825-3-729654382 systemd[1]: m3dbnode.service holdoff time over, scheduling restart.
Aug 18 21:35:48 dbnode-500173825-3-729654382 systemd[1]: Started "M3DB Timeseries Database".
Aug 18 21:35:48 dbnode-500173825-3-729654382 systemd[1]: Starting "M3DB Timeseries Database"...
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Go Runtime version: go1.13.12
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Build Version:      v0.15.6-vellum_case_fix
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Build Revision:     ff17acb3e
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Build Branch:       HEAD
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Build Date:         2020-08-12-21:11:02
Aug 18 21:35:48 dbnode-500173825-3-729654382 m3dbnode[104689]: 2020/08/18 21:35:48 Build TimeUnix:     1597266662
```

**Comment by nicklan** [comment]
We are seeing the same issue:

```
2020/08/17 06:24:52 Go Runtime version: go1.13.14
2020/08/17 06:24:52 Build Version:      v0.15.6
2020/08/17 06:24:52 Build Revision:     ff17acb3e
2020/08/17 06:24:52 Build Branch:       HEAD
2020/08/17 06:24:52 Build Date:         2020-07-24-17:35:19
2020/08/17 06:24:52 Build TimeUnix:     1595612119
```

```
unexpected fault address 0x7e6c9f0c5603
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7e6c9f0c5603 pc=0xc492d7]

goroutine 21408810267 [running]:
runtime.throw(0x1d9e678, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc4bde87110 sp=0xc4bde870e0 pc=0x42f552
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc4bde87140 sp=0xc4bde87110 pc=0x444c8e
github.com/m3dbx/vellum.(*fstStateV1).isEncodedSingle(...)
        /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/decoder_v1.go:100
github.com/m3dbx/vellum.(*fstStateV1).TransitionAt(0xc97a6a2500, 0x1, 0x40)
        /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/decoder_v1.go:231 +0x27 fp=0xc4bde87160 sp=0xc4bde87140 pc=0xc492d7
github.com/m3dbx/vellum.(*FSTIterator).next(0xc9790dd000, 0xffffffffffffffff, 0x20, 0x1ba1d40)
        /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:243 +0x120 fp=0xc4bde87240 sp=0xc4bde87160 pc=0xc4e110
github.com/m3dbx/vellum.(*FSTIterator).Next(...)
        /go/pkg/mod/github.com/m3dbx/vellum@v0.0.0-20200602203954-e10aaedbd934/fst_iterator.go:219
github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsIter).Next(0xc97a162fa0, 0xc06486e800)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_iterator.go:94 +0xbc fp=0xc4bde87288 sp=0xc4bde87240 pc=0xc6dedc
github.com/m3db/m3/src/m3ninx/index/segment/fst.(*fstTermsPostingsIter).Next(0xc97a427c20, 0x1b58360)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/fst/fst_terms_postings_iterator.go:90 +0x3e fp=0xc4bde872c0 sp=0xc4bde87288 pc=0xc6e79e
github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).nextTermsIterResult(0xc97a41e6e0, 0x10000c9153e1801, 0x0, 0x0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:223 +0x38 fp=0xc4bde87300 sp=0xc4bde872c0 pc=0xcd7ab8
github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).setNext(0xc97a41e6e0, 0x80)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:182 +0x1f7 fp=0xc4bde87350 sp=0xc4bde87300 pc=0xcd7a07
github.com/m3db/m3/src/dbnode/storage/index.(*fieldsAndTermsIter).Next(0xc97a41e6e0, 0xc06486e800)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/fields_terms_iterator.go:265 +0x38 fp=0xc4bde87370 sp=0xc4bde87350 pc=0xcd7d18
github.com/m3db/m3/src/dbnode/storage/index.(*block).aggregateWithSpan(0xc45f182840, 0x218ae00, 0xc5f732d730, 0xc134f71a00, 0x7ab1e00, 0xce288ee1d, 0x30392a0, 0x96766f, 0xed6cc19a1, 0x30392a0, ...)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:680 +0x41b fp=0xc4bde87758 sp=0xc4bde87370 pc=0xcd266b
github.com/m3db/m3/src/dbnode/storage/index.(*block).Aggregate(0xc45f182840, 0x218ae00, 0xc5f732d730, 0xc134f71a00, 0x7ab1e00, 0xce288ee1d, 0x30392a0, 0x96766f, 0xed6cc19a1, 0x30392a0, ...)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:592 +0x1c3 fp=0xc4bde87900 sp=0xc4bde87758 pc=0xcd2023
github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn(0xc0a7b83c00, 0x218ae00, 0xc5f732d730, 0xc134f71a00, 0x21921e0, 0xc45f182840, 0x21658c0, 0xc97858fea0, 0x7ab1e00, 0xce288ee1d, ...)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1663 +0x8fe fp=0xc4bde87da0 sp=0xc4bde87900 pc=0x108b18e
github.com/m3db/m3/src/dbnode/storage.(*nsIndex).execBlockAggregateQueryFn-fm(0x218ae00, 0xc5f732d730, 0xc134f71a00, 0x21921e0, 0xc45f182840, 0x21658c0, 0xc97858fea0, 0x7ab1e00, 0xce288ee1d, 0x30392a0, ...)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1635 +0x124 fp=0xc4bde87e78 sp=0xc4bde87da0 pc=0x10e0844
github.com/m3db/m3/src/dbnode/storage.(*nsIndex).queryWithSpan.func2()
        /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:1531 +0x150 fp=0xc4bde87fb0 sp=0xc4bde87e78 pc=0x10ce610
github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout.func1(0xc41d5959e0, 0xc00092e020)
        /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:68 +0x27 fp=0xc4bde87fd0 sp=0xc4bde87fb0 pc=0xc10107
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc4bde87fd8 sp=0xc4bde87fd0 pc=0x45efe1
created by github.com/m3db/m3/src/x/sync.(*workerPool).GoWithTimeout
        /go/src/github.com/m3db/m3/src/x/sync/worker_pool.go:67 +0x122
```

**Comment by robskillington** [comment]
Hey thanks a lot for the reports, this was fixed with https://github.com/m3db/m3/pull/2550 and releases v0.15.11 and onwards contain the fix. 

All bugs related to this indexing lifecycle now have extensive integration stress tests to ensure anything similar of this nature is ever introduced it will be detected.

Thanks again.
