### ISSUE TITLE
invalid memory address or nil pointer dereference in storage writeSingle()

### ISSUE THREAD

**Issue by dennisjac** [m3db/m3#2983]
Hi, I'm want to experiment with M3 and set up a small single node instance that includes Prometheus but it seems the moment Prometheus wants to write to the remote_write endpoint m3db crashes:
```
2020/12/04 21:47:14 Go Runtime version: go1.13.15
2020/12/04 21:47:14 Build Version:      v1.0.0
2020/12/04 21:47:14 Build Revision:     a3853ee56
2020/12/04 21:47:14 Build Branch:       HEAD
2020/12/04 21:47:14 Build Date:         2020-11-17-23:19:06
2020/12/04 21:47:14 Build TimeUnix:     1605655146
{"level":"info","ts":1607118435.0102608,"msg":"setting MutexProfileFraction: 0"}
{"level":"info","ts":1607118435.010289,"msg":"setting BlockProfileRate: 0"}
{"level":"info","ts":1607118435.0104065,"msg":"setting MutexProfileFraction: 0"}
{"level":"info","ts":1607118435.0104232,"msg":"setting BlockProfileRate: 0"}
{"level":"warn","ts":1607118435.010501,"msg":"unable to raise rlimit","error":"unable to raise nofile limits: rlimit_set_err=operation not permitted"}
{"level":"warn","ts":1607118435.0109053,"msg":"invalid configuration found, refer to linked documentation for more information","url":"https://docs.m3db.io/operational_guide/kernel_configuration","error":"current value for vm.max_map_count(65530) is below recommended threshold(3000000)\ncurrent value for vm.swappiness(60) is above recommended threshold(1)","errorCauses":[{"error":"current value for vm.swappiness(60) is above recommended threshold(1)"},{"error":"current value for vm.max_map_count(65530) is below recommended threshold(3000000)"}]}
{"level":"info","ts":1607118435.0115478,"msg":"tracing disabled for m3query; set `tracing.backend` to enable"}
{"level":"info","ts":1607118435.0116637,"msg":"tracing disabled; set `tracing.backend` to enable"}
{"level":"info","ts":1607118435.011686,"msg":"resolving seed node configuration","hostID":"m3db_local","seedNodeHostIDs":["m3db_local"]}
{"level":"info","ts":1607118435.0116997,"msg":"seed node, starting etcd server"}
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-12-04 21:47:15.011823 I | embed: name = m3db_local
2020-12-04 21:47:15.011834 I | embed: data dir = /var/lib/m3db/etcd
2020-12-04 21:47:15.011838 I | embed: member dir = /var/lib/m3db/etcd/member
2020-12-04 21:47:15.011841 I | embed: heartbeat = 100ms
2020-12-04 21:47:15.011844 I | embed: election = 1000ms
2020-12-04 21:47:15.011846 I | embed: snapshot count = 100000
2020-12-04 21:47:15.011852 I | embed: advertise client URLs = http://127.0.0.1:2379
2020-12-04 21:47:15.031671 I | etcdserver: starting member b71f75320dc06a6c in cluster 1c45a069f3a1d796
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c switched to configuration voters=()
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c became follower at term 0
raft2020/12/04 21:47:15 INFO: newRaft b71f75320dc06a6c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c became follower at term 1
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c switched to configuration voters=(13195394291058371180)
2020-12-04 21:47:15.041087 W | auth: simple token is not cryptographically signed
2020-12-04 21:47:15.053444 I | etcdserver: starting server... [version: 3.4.13, cluster version: to_be_decided]
2020-12-04 21:47:15.053552 I | etcdserver: b71f75320dc06a6c as single-node; fast-forwarding 9 ticks (election ticks 10)
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c switched to configuration voters=(13195394291058371180)
2020-12-04 21:47:15.054012 I | etcdserver/membership: added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 1c45a069f3a1d796
2020-12-04 21:47:15.056119 I | embed: listening for peers on [::]:2380
{"level":"info","ts":1607118435.0701823,"msg":"successfully created new cache dir","path":"/var/lib/m3kv","mode":0}
{"level":"warn","ts":1607118435.070385,"msg":"could not load cache from file","file":"/var/lib/m3kv/_kv_default_env_m3db_embedded.json","error":"error opening cache file /var/lib/m3kv/_kv_default_env_m3db_embedded.json: open /var/lib/m3kv/_kv_default_env_m3db_embedded.json: no such file or directory"}
{"level":"info","ts":1607118435.0910327,"msg":"creating namespaces watcher","clusters":1}
{"level":"warn","ts":1607118435.2457001,"msg":"max index query IDs concurrency was not set, falling back to default value"}
{"level":"warn","ts":1607118435.2458513,"msg":"host doesn't support HugeTLB, proceeding without it"}
{"level":"info","ts":1607118435.25965,"msg":"set thrift bytes pool alloc size","size":2048}
{"level":"info","ts":1607118435.259686,"msg":"bytes pool configured","capacity":16,"size":524288,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.2596908,"msg":"bytes pool configured","capacity":32,"size":262144,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.2596934,"msg":"bytes pool configured","capacity":64,"size":131072,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.2596953,"msg":"bytes pool configured","capacity":128,"size":65536,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.2596974,"msg":"bytes pool configured","capacity":256,"size":65536,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.259699,"msg":"bytes pool configured","capacity":1440,"size":16384,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.2597017,"msg":"bytes pool configured","capacity":4096,"size":8192,"refillLowWaterMark":0.3,"refillHighWaterMark":0.6}
{"level":"info","ts":1607118435.25975,"msg":"bytes pool init start"}
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c is starting a new election at term 1
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c became candidate at term 2
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c received MsgVoteResp from b71f75320dc06a6c at term 2
raft2020/12/04 21:47:15 INFO: b71f75320dc06a6c became leader at term 2
raft2020/12/04 21:47:15 INFO: raft.node: b71f75320dc06a6c elected leader b71f75320dc06a6c at term 2
2020-12-04 21:47:15.332251 I | etcdserver: setting up the initial cluster version to 3.4
2020-12-04 21:47:15.334527 N | etcdserver/membership: set the initial cluster version to 3.4
2020-12-04 21:47:15.334572 I | etcdserver/api: enabled capabilities for version 3.4
2020-12-04 21:47:15.334599 I | etcdserver: published {Name:m3db_local ClientURLs:[http://127.0.0.1:2379]} to cluster 1c45a069f3a1d796
2020-12-04 21:47:15.334611 I | embed: ready to serve client requests
2020-12-04 21:47:15.335200 N | embed: serving insecure client requests on [::]:2379, this is strongly discouraged!
{"level":"info","ts":1607118435.337036,"msg":"no initial namespaces found. namespaces will be added via watch updates"}
{"level":"info","ts":1607118435.337179,"msg":"configuring downsampler to use with aggregated cluster namespaces","numAggregatedClusterNamespaces":0}
{"level":"info","ts":1607118435.3435392,"msg":"","level":"debug","component":"prometheus_engine","msg":"lookback delta is zero, setting to default value","value":300}
{"level":"info","ts":1607118435.3449113,"msg":"no m3msg server configured"}
{"level":"info","ts":1607118435.3449183,"msg":"using registered interrupt handler"}
{"level":"info","ts":1607118435.3449314,"msg":"starting API server","address":"[::]:7201"}
{"level":"info","ts":1607118435.5980937,"msg":"bytes pool init end"}
{"level":"info","ts":1607118435.7850318,"msg":"creating dynamic config service client with m3cluster"}
{"level":"info","ts":1607118435.7853515,"msg":"successfully created new cache dir","path":"/var/lib/m3kv","mode":493}
{"level":"warn","ts":1607118435.7856832,"msg":"could not load cache from file","file":"/var/lib/m3kv/_kv_default_env_m3db_embedded.json","error":"error opening cache file /var/lib/m3kv/_kv_default_env_m3db_embedded.json: open /var/lib/m3kv/_kv_default_env_m3db_embedded.json: no such file or directory"}
{"level":"info","ts":1607118435.991178,"msg":"node tchannelthrift: listening","address":"0.0.0.0:9000"}
{"level":"info","ts":1607118435.9914405,"msg":"node httpjson: listening","address":"0.0.0.0:9002"}
{"level":"info","ts":1607118435.9914997,"msg":"waiting for dynamic topology initialization, if this takes a long time, make sure that a topology/placement is configured"}
{"level":"info","ts":1607118435.9915092,"msg":"adding a watch","service":"m3db","env":"default_env","zone":"embedded","includeUnhealthy":true}
{"level":"info","ts":1607118435.9915931,"msg":"successfully created new cache dir","path":"/var/lib/m3kv","mode":493}
{"level":"warn","ts":1607118435.991634,"msg":"could not load cache from file","file":"/var/lib/m3kv/m3db_embedded.json","error":"error opening cache file /var/lib/m3kv/m3db_embedded.json: open /var/lib/m3kv/m3db_embedded.json: no such file or directory"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12e8a4b]
goroutine 10169 [running]:
github.com/m3db/m3/src/query/storage/m3.(*m3storage).writeSingle(0xc06d4508a0, 0x22f1ae0, 0xc094652300, 0xc09460c280, 0x20b91340, 0xed75ca568, 0x32a1140, 0x0, 0x230a7e0, 0xc0933e6a40, ...)
	/go/src/github.com/m3db/m3/src/query/storage/m3/storage.go:720 +0x11b
github.com/m3db/m3/src/query/storage/m3.(*m3storage).Write(0xc06d4508a0, 0x22f1ae0, 0xc094652300, 0xc09460c280, 0x22ceee0, 0xc09460c280)
	/go/src/github.com/m3db/m3/src/query/storage/m3/storage.go:635 +0x7b8
github.com/m3db/m3/src/query/storage/fanout.(*fanoutStorage).Write(0xc06da9a3c0, 0x22f1ae0, 0xc094652300, 0xc09460c280, 0x3, 0x0)
	/go/src/github.com/m3db/m3/src/query/storage/fanout/storage.go:422 +0x2f4
github.com/m3db/m3/src/cmd/services/m3coordinator/ingest.(*downsamplerAndWriter).WriteBatch.func2()
	/go/src/github.com/m3db/m3/src/cmd/services/m3coordinator/ingest/write.go:416 +0x252
github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc06dabcd90, 0x0, 0x15f1598415f15984, 0xc00580cde0, 0x1e4f801)
	/go/src/github.com/m3db/m3/src/x/sync/pooled_worker_pool.go:177 +0x18c
created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
	/go/src/github.com/m3db/m3/src/x/sync/pooled_worker_pool.go:156 +0x66
```
I'm using a docker-compose file to set this up:
```
version: "3.7"

services:
  m3db:
    container_name: m3db
    image: quay.io/m3db/m3dbnode:v1.0.0
    ports:
    - "7201:7201"
    - "7203:7203"
    volumes:
    - m3db-data:/var/lib/m3db
    ulimits:
      nofile:
        soft: 3000000
        hard: 3000000

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.23.0
    ports:
    - "9090:9090"
    volumes:
    - m3db-prometheus-config:/etc/prometheus

volumes:
  m3db-data:
    external: true
  m3db-prometheus-config:
    external: true
```
The `m3db-data` volume is empty on start and the `m3db-prometheus-config` contains the following minimal config:
```
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'm3db'
    static_configs:
      - targets: ['m3db:7203']

remote_read:
  - url: "http://m3db:7201/api/v1/prom/remote/read"
    # To test reading even when local Prometheus has the data
    read_recent: true

remote_write:
  - url: "http://m3db:7201/api/v1/prom/remote/write"
```

**Comment by robskillington** [comment]
Hey thanks for the bug report @dennisjac, basically the namespace has not been readied and this was causing a panic instead of an error.

That panic is now safely avoided and merged to master:
https://github.com/m3db/m3/commit/4bfe37732aa8763eeb97af9cc8e31ee1d6aed9d5

To ready your namespace follow the steps from the Docker quickstart under "Ready a Namespace":
https://m3db.io/docs/quickstart/docker/

Thanks again for opening the issue, let us know if you have any further issues.
