### ISSUE TITLE
Quickstart doc seems be at fault

### ISSUE THREAD

**Issue by praisethejack** [m3db/m3#3568]
m3dbnode
I just follow https://m3db.io/docs/quickstart/binaries/, but when i **Writing Metrics**, m3node reports a heap of error and then exit. There is some of them:
```
goroutine 14088 [chan receive]:
github.com/m3db/m3/src/dbnode/storage.(*mediatorTimeBarrier).fsProcessesWait(0xc009f9b4d0, 0xc00073e540, 0xc00699c540, 0x32b7f80, 0x1, 0x0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:436 +0x7c
github.com/m3db/m3/src/dbnode/storage.(*mediator).runColdFlushProcesses(0xc009f9b400)
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:314 +0x85
github.com/m3db/m3/src/dbnode/storage.(*mediator).ongoingColdFlushProcesses(0xc009f9b400)
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:260 +0x31
created by github.com/m3db/m3/src/dbnode/storage.(*mediator).Open
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:151 +0xef

goroutine 14089 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:105 +0x157
github.com/m3db/m3/src/dbnode/storage.(*tickManager).Tick(0xc00a12a000, 0x1, 0xc02cc2975be8f89c, 0x51ec8ca259, 0x32b7f80, 0x0, 0x0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/tick.go:194 +0x534
github.com/m3db/m3/src/dbnode/storage.(*mediator).ongoingTick(0xc009f9b400)
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:292 +0x329
created by github.com/m3db/m3/src/dbnode/storage.(*mediator).Open
        /go/src/github.com/m3db/m3/src/dbnode/storage/mediator.go:152 +0x111

goroutine 14090 [select, 5 minutes]:
github.com/m3db/m3/src/dbnode/storage/cluster.(*clusterDB).activeTopologyWatch(0xc0c92c3dc0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/cluster/database.go:311 +0x250
created by github.com/m3db/m3/src/dbnode/storage/cluster.(*clusterDB).startActiveTopologyWatch
        /go/src/github.com/m3db/m3/src/dbnode/storage/cluster/database.go:263 +0x11e

goroutine 14782 [select, 5 minutes]:
go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch(0xc005d3a370, 0x2325120, 0xc0a25f3410, 0x22bdb00, 0xc005d3a370)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/etcdserver/api/v3rpc/watch.go:209 +0x3a2
go.etcd.io/etcd/etcdserver/etcdserverpb._Watch_Watch_Handler(0x1bb1700, 0xc005d3a370, 0x23190c0, 0xc09f83c5c0, 0x40ca88, 0x20)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/etcdserver/etcdserverpb/rpc.pb.go:3726 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x1bb1700, 0xc005d3a370, 0x23190c0, 0xc09f83c5c0, 0x19, 0xc009f4b9f0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:71 +0xf1
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0x1bb1700, 0xc005d3a370, 0x231c2a0, 0xc00b79a0c0, 0xc09f83c580, 0xc009f4b9a0, 0x42e3ba, 0xc00b79a0c0)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0xeb
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x1bb1700, 0xc005d3a370, 0x231c2a0, 0xc00b79a0c0, 0xc0a25f33c0, 0xc05819c480)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:74 +0x99
go.etcd.io/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1(0x1bb1700, 0xc005d3a370, 0x231c2a0, 0xc00b79a0c0, 0xc09f83c580, 0xc009f4b9a0, 0x0, 0x0)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/etcdserver/api/v3rpc/interceptor.go:236 +0x14e
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x1bb1700, 0xc005d3a370, 0x231b220, 0xc00b8335c0, 0xc09f83c580, 0x1f9b3f8, 0x2303520, 0xc00b79a060)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:79 +0x14f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000176b60, 0x2328600, 0xc092b48000, 0xc06299d200, 0xc005d4ea20, 0x3295420, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1336 +0x486
google.golang.org/grpc.(*Server).handleStream(0xc000176b60, 0x2328600, 0xc092b48000, 0xc06299d200, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xcbe
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc062a22060, 0xc000176b60, 0x2328600, 0xc092b48000, 0xc06299d200)
        /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1
```
```
goroutine 15527 [chan receive, 5 minutes]:
github.com/m3db/m3/src/dbnode/namespace.(*runtimeOptionsManager).RegisterListener.func1(0x22f3ba0, 0xc00f339b00, 0x22bc0c0, 0xc00a2ccb40)
        /go/src/github.com/m3db/m3/src/dbnode/namespace/namespace_runtime_options.go:244 +0xa5
created by github.com/m3db/m3/src/dbnode/namespace.(*runtimeOptionsManager).RegisterListener
        /go/src/github.com/m3db/m3/src/dbnode/namespace/namespace_runtime_options.go:243 +0xf9

goroutine 15541 [chan receive, 5 minutes]:
github.com/m3db/m3/src/dbnode/namespace.(*runtimeOptionsManager).RegisterListener.func1(0x22f3ba0, 0xc00f3b33b0, 0x22bc0c0, 0xc00a2cdcc0)
        /go/src/github.com/m3db/m3/src/dbnode/namespace/namespace_runtime_options.go:244 +0xa5
created by github.com/m3db/m3/src/dbnode/namespace.(*runtimeOptionsManager).RegisterListener
        /go/src/github.com/m3db/m3/src/dbnode/namespace/namespace_runtime_options.go:243 +0xf9

rax    0xc009ed8790
rbx    0xc009ed8790
rcx    0xc00b77f200
rdx    0xc00f1169a0
rdi    0xc00f82c3c0
rsi    0xc00f82c570
rbp    0xc00f82c278
rsp    0xc00f82c210
r8     0x0
r9     0x203003
r10    0x14
r11    0xfc
r12    0xfc
r13    0x0
r14    0x227f6d4
r15    0x0
rip    0xd01c10
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0
[root@node1 m3_1.1.0_linux_amd64]
```

**Comment by gibbscullen** [comment]
@praisethejack are you still having an issue with the quickstart guide?
