### ISSUE TITLE
Data race in TestBlockRetrieverHighConcurrentSeeksCacheShardIndices 

### ISSUE THREAD

**Issue by prateek** [m3db/m3#586]
```
==================
WARNING: DATA RACE
Read at 0x00c4204c4080 by goroutine 27:
  github.com/m3db/m3db/persist/fs.(*seekerManager).newOpenSeeker()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:363 +0xa7
  github.com/m3db/m3db/persist/fs.(*seekerManager).(github.com/m3db/m3db/persist/fs.newOpenSeeker)-fm()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:132 +0x74
  github.com/m3db/m3db/persist/fs.(*seekerManager).getOrOpenSeekersWithLock()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:300 +0x439
  github.com/m3db/m3db/persist/fs.(*seekerManager).openAnyUnopenSeekers()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:349 +0x390
  github.com/m3db/m3db/persist/fs.(*seekerManager).(github.com/m3db/m3db/persist/fs.openAnyUnopenSeekers)-fm()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:131 +0x4b
  github.com/m3db/m3db/persist/fs.(*seekerManager).openCloseLoop()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:530 +0x43d

Previous write at 0x00c4204c4080 by goroutine 147:
  github.com/m3db/m3db/persist/fs.(*seekerManager).Close()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:461 +0x3f5
  github.com/m3db/m3db/persist/fs.(*blockRetriever).Close()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever.go:470 +0x216
  github.com/m3db/m3db/persist/fs.newOpenTestBlockRetriever.func1()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:73 +0x4e
  github.com/m3db/m3db/persist/fs.testBlockRetrieverHighConcurrentSeeks()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:262 +0x1786
  github.com/m3db/m3db/persist/fs.TestBlockRetrieverHighConcurrentSeeksCacheShardIndices()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:120 +0x3d
  testing.tRunner()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:777 +0x16d

Goroutine 27 (running) created at:
  github.com/m3db/m3db/persist/fs.(*seekerManager).Open()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:151 +0x1ae
  github.com/m3db/m3db/persist/fs.(*blockRetriever).Open()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever.go:134 +0x1d7
  github.com/m3db/m3db/persist/fs.newOpenTestBlockRetriever()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:70 +0x283
  github.com/m3db/m3db/persist/fs.testBlockRetrieverHighConcurrentSeeks()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:143 +0x370
  github.com/m3db/m3db/persist/fs.TestBlockRetrieverHighConcurrentSeeksCacheShardIndices()
      /home/runner/workspace/src/github.com/m3db/m3db/persist/fs/retriever_concurrent_test.go:120 +0x3d
  testing.tRunner()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:777 +0x16d

Goroutine 147 (running) created at:
  testing.(*T).Run()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:824 +0x564
  testing.runTests.func1()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:1063 +0xa4
  testing.tRunner()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:777 +0x16d
  testing.runTests()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:1061 +0x4e1
  testing.(*M).Run()
      /home/runner/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:978 +0x2cd
  main.main()
      _testmain.go:264 +0x324
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9318df]

goroutine 110604 [running]:
github.com/m3db/m3db/persist/fs.NamespaceDataDirPath(0xc420bc6040, 0x14, 0x0, 0x0, 0xb19b80, 0xc420081418)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/files.go:706 +0x4f
github.com/m3db/m3db/persist/fs.ShardDataDirPath(0xc420bc6040, 0x14, 0x0, 0x0, 0x1, 0xab5c61, 0xa)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/files.go:726 +0x7f
github.com/m3db/m3db/persist/fs.DataFileSetExistsAt(0xc420bc6040, 0x14, 0x0, 0x0, 0x1, 0x0, 0xed27e96a0, 0xdafce0, 0x4159b0)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/files.go:743 +0x7e
github.com/m3db/m3db/persist/fs.(*seekerManager).newOpenSeeker(0xc4204c4000, 0x1, 0x0, 0xed27e96a0, 0xdafce0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:363 +0x110
github.com/m3db/m3db/persist/fs.(*seekerManager).(github.com/m3db/m3db/persist/fs.newOpenSeeker)-fm(0xc400000001, 0x0, 0xed27e96a0, 0xdafce0, 0x0, 0x4, 0xb194c0, 0xc42035d800)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:132 +0x75
github.com/m3db/m3db/persist/fs.(*seekerManager).getOrOpenSeekersWithLock(0xc4204c4000, 0x152b82e09c344000, 0xc420367530, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb194c0, 0xc42035d800)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:300 +0x43a
github.com/m3db/m3db/persist/fs.(*seekerManager).openAnyUnopenSeekers(0xc4204c4000, 0xc420367530, 0x0, 0x0)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:349 +0x391
github.com/m3db/m3db/persist/fs.(*seekerManager).(github.com/m3db/m3db/persist/fs.openAnyUnopenSeekers)-fm(0xc420367530, 0x1, 0x68)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:131 +0x4c
github.com/m3db/m3db/persist/fs.(*seekerManager).openCloseLoop(0xc4204c4000)
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:530 +0x43e
created by github.com/m3db/m3db/persist/fs.(*seekerManager).Open
	/home/runner/workspace/src/github.com/m3db/m3db/persist/fs/seek_manager.go:151 +0x1af
FAIL	github.com/m3db/m3db/persist/fs	37.213s
```

**Comment by richardartoul** [comment]
Thanks, I've seen this one flake before but never managed to get it to fire under the race detector. Will take a look this week
