### ISSUE TITLE
Investigate flaky test: TestRegexpCompilationProperty

### ISSUE THREAD

**Issue by prateek** [m3db/m3#941]
```
=== RUN   TestRegexpCompilationProperty
! Regexp matches same strings after modifications: Error on property evaluation after 73190 passed tests: Check paniced: reflect: Call using zero Value
   argument goroutine 6 [running]:
runtime/debug.Stack(0xc42007d1e8, 0x7aede0, 0xc420818980)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
github.com/m3db/m3/vendor/github.com/leanovate/gopter.SaveProp.func1.1(0xc42007dce8)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop.go:19 +0x6e
panic(0x7aede0, 0xc420818980)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/runtime/panic.go:502 +0x229
reflect.Value.call(0x7c1600, 0xc420818940, 0x13, 0x84e4be, 0x4, 0xc42007d630, 0x1, 0x1, 0x4124b8, 0x20, ...)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/reflect/value.go:372 +0x12ab
reflect.Value.Call(0x7c1600, 0xc420818940, 0x13, 0xc42007d630, 0x1, 0x1, 0x741ebf, 0xc420692c40, 0xc42048f3b0)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/m3db/m3/vendor/github.com/leanovate/gopter.Gen.SuchThat.func1(0x0, 0x0, 0x86af28)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/gen.go:67 +0x9f
github.com/m3db/m3/vendor/github.com/leanovate/gopter.(*GenResult).Retrieve(0xc42048f3b0, 0xc42048f3b0, 0xc42033a3a0, 0x16)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/gen_result.go:39 +0x5e
github.com/m3db/m3/src/m3ninx/index.genInputCase.func1(0xc420310480, 0x87, 0xc420692c40, 0x0)
	/home/runner/workspace/src/github.com/m3db/m3/src/m3ninx/index/regexp_prop_test.go:93 +0x5a
reflect.Value.call(0x7c9340, 0x86a750, 0x13, 0x84e4be, 0x4, 0xc42007dae8, 0x2, 0x2, 0x7aede0, 0x7fa840, ...)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x7c9340, 0x86a750, 0x13, 0xc42007dae8, 0x2, 0x2, 0x0, 0x8, 0x8)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/m3db/m3/vendor/github.com/leanovate/gopter.Gen.Map.func1(0xc420692c40, 0x442c57)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/gen.go:157 +0x537
github.com/m3db/m3/vendor/github.com/leanovate/gopter.Gen.SuchThat.func2(0xc420692c40, 0x1)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/gen.go:71 +0x3f
github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop.ForAll.func1(0xc420692c40, 0x86af00)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop/forall.go:31 +0x140
github.com/m3db/m3/vendor/github.com/leanovate/gopter.SaveProp.func1(0xc420692c40, 0x0)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop.go:24 +0x6c
github.com/m3db/m3/vendor/github.com/leanovate/gopter.Prop.Check.func1(0x0, 0xc4203d81d0, 0xaa3a00)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop.go:52 +0x15c
github.com/m3db/m3/vendor/github.com/leanovate/gopter.(*runner).runWorkers(0xc42031d320, 0x0)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/runner.go:49 +0x2d9
github.com/m3db/m3/vendor/github.com/leanovate/gopter.Prop.Check(0xc4203d81b0, 0xc42003a1c0, 0x85f3dd)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/prop.go:110 +0x1af
github.com/m3db/m3/vendor/github.com/leanovate/gopter.(*Properties).Run(0xc42031c4e0, 0x89be40, 0xc4203d4f20, 0x2f)
	/home/runner/workspace/src/github.com/m3db/m3/vendor/github.com/leanovate/gopter/properties.go:37 +0xc9
github.com/m3db/m3/src/m3ninx/index.TestRegexpCompilationProperty(0xc4203600f0)
	/home/runner/workspace/src/github.com/m3db/m3/src/m3ninx/index/regexp_prop_test.go:72 +0x36e
testing.tRunner(0xc4203600f0, 0x86a748)
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/runner/.gimme/versions/go1.10.4.linux.amd64/src/testing/testing.go:824 +0x2e0


Elapsed time: 5.682185707s
--- FAIL: TestRegexpCompilationProperty (5.68s)
	regexp_prop_test.go:73: failed with initial seed: 1537893865431120295
```

**Comment by prateek** [comment]
Tracked down to an issue in gopter, put up a fix there.

**Comment by prateek** [comment]
Landed fix on master
